services:
  - type: web
    name: bible-quest-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 5050
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: BIBLE_API_KEY
        sync: false 